openapi: 3.0.0
info:
  title: Hello API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Say hello
      operationId: getHello
      parameters:
        - name: message
          in: query
          description: The greeting message (non-null, required)
          required: true
          schema:
            type: string
            example: "Hello, world!"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

components:
  schemas:
    MessageResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The greeting message
          example: "Hello, world!"
